nginx:
    image: nginx:latest
    ports:
        - 8009:80
    links:
        - php
    volumes_from:
        - app-data
    volumes:
        - ./docker-conf/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    environment:
        - VIRTUAL_HOST=football-poc.localhost

php:
    build: ./docker-conf/php/
    links:
        - mysql
    expose:
        - 9000
    volumes_from:
        - app-data
    volumes:
        - ./docker-conf/php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./docker-conf/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/custom.conf
        - ./docker-conf/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
        XDEBUG_CONFIG: "remote_host=docker.for.mac.host.internal"
        PHP_IDE_CONFIG: "serverName=football-poc"

app-data:
    image: tianon/true
    volumes:
        - .:/var/www/html

mysql:
    image: mysql:latest
    ports:
      - 33068:3306
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: football-poc.db
        MYSQL_USER: football-poc
        MYSQL_PASSWORD: football-poc

data:
    image: tianon/true
    volumes:
        - /var/lib/mysql

nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
        - 80:80
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro